= About API Functional Monitoring

You use API functional monitoring to run a test or suite of tests on an API. API functional monitoring is based on Bash Automated Testing (BAT). 

Refer to the bat demo for a substantial example of a BAT test suite. Clone the BAT demo at the following location:

`+https://github.com/mulesoft/bat-demo+`

Using API functional monitoring, you can automate testing and get test reports. You can test before pushing code into your repository and before deploying to production. Tests can verify API functionality and validate results the API generates. You can monitor APIs at each stage of the software development life cycle and in production.

The prerequisites for performing API functional monitoring are:

* Deployed API
+
You can deploy an API on Anypoint Platform or your own server. 
* Installation of bat-wrapper 
* A YAML configuration file (manifest file)
* At least one test file
+
** You write files in BDD syntax using a code or text editor, such as IntelliJ.
** You save the files using .dwl extension for processing by DataWeave.



